'use client'

import { useEffect } from 'react'

// iOS Splash Screen configurations based on actual files generated by pwa-asset-generator
// Format: { mediaQuery, filename } - files are in format width-height.jpg
const splashScreens = [
  // iPhone 14 Pro Max, iPhone 13 Pro Max, iPhone 12 Pro Max (430x932 @3x = 1290x2796)
  { media: '(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)', file: 'apple-splash-1290-2796.jpg' },
  { media: '(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)', file: 'apple-splash-2796-1290.jpg' },
  
  // iPhone 14 Pro, iPhone 13 Pro, iPhone 12 Pro (393x852 @3x = 1179x2556)
  { media: '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)', file: 'apple-splash-1179-2556.jpg' },
  { media: '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)', file: 'apple-splash-2556-1179.jpg' },
  
  // iPhone 14 Plus (428x926 @3x = 1284x2778)
  { media: '(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)', file: 'apple-splash-1284-2778.jpg' },
  { media: '(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)', file: 'apple-splash-2778-1284.jpg' },
  
  // iPhone 14, iPhone 13, iPhone 12 (390x844 @3x = 1170x2532)
  { media: '(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)', file: 'apple-splash-1170-2532.jpg' },
  { media: '(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)', file: 'apple-splash-2532-1170.jpg' },
  
  // iPhone 11 Pro Max, iPhone XS Max (414x896 @3x = 1242x2688)
  { media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)', file: 'apple-splash-1242-2688.jpg' },
  { media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)', file: 'apple-splash-2688-1242.jpg' },
  
  // iPhone 11 Pro, iPhone XS, iPhone X (375x812 @3x = 1125x2436)
  { media: '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)', file: 'apple-splash-1125-2436.jpg' },
  { media: '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)', file: 'apple-splash-2436-1125.jpg' },
  
  // iPhone 11, iPhone XR (414x896 @2x = 828x1792)
  { media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)', file: 'apple-splash-828-1792.jpg' },
  { media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)', file: 'apple-splash-1792-828.jpg' },
  
  // iPhone 8 Plus, iPhone 7 Plus, iPhone 6s Plus (414x736 @3x = 1242x2208)
  { media: '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)', file: 'apple-splash-1242-2208.jpg' },
  { media: '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)', file: 'apple-splash-2208-1242.jpg' },
  
  // iPhone 8, iPhone 7, iPhone 6s, iPhone 6 (375x667 @2x = 750x1334)
  { media: '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)', file: 'apple-splash-750-1334.jpg' },
  { media: '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)', file: 'apple-splash-1334-750.jpg' },
  
  // iPhone SE (320x568 @2x = 640x1136)
  { media: '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)', file: 'apple-splash-640-1136.jpg' },
  { media: '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)', file: 'apple-splash-1136-640.jpg' },
  
  // iPad Pro 12.9" (1024x1366 @2x = 2048x2732)
  { media: '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)', file: 'apple-splash-2048-2732.jpg' },
  { media: '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)', file: 'apple-splash-2732-2048.jpg' },
  
  // iPad Pro 11" (834x1194 @2x = 1668x2388)
  { media: '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)', file: 'apple-splash-1668-2388.jpg' },
  { media: '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)', file: 'apple-splash-2388-1668.jpg' },
  
  // iPad Pro 10.5" (834x1112 @2x = 1668x2224)
  { media: '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)', file: 'apple-splash-1668-2224.jpg' },
  { media: '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)', file: 'apple-splash-2224-1668.jpg' },
  
  // iPad Air, iPad Mini (768x1024 @2x = 1536x2048)
  { media: '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)', file: 'apple-splash-1536-2048.jpg' },
  { media: '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)', file: 'apple-splash-2048-1536.jpg' },
  
  // Additional iPad sizes
  { media: '(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)', file: 'apple-splash-1620-2160.jpg' },
  { media: '(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)', file: 'apple-splash-2160-1620.jpg' },
  
  { media: '(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)', file: 'apple-splash-1640-2360.jpg' },
  { media: '(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)', file: 'apple-splash-2360-1640.jpg' },
]

export default function AppleSplashScreens() {
  useEffect(() => {
    // Add splash screen link tags to the head
    splashScreens.forEach((screen) => {
      const link = document.createElement('link')
      link.rel = 'apple-touch-startup-image'
      link.href = `/${screen.file}`
      link.media = screen.media
      document.head.appendChild(link)
    })

    // Cleanup function to remove links when component unmounts
    return () => {
      const links = document.querySelectorAll('link[rel="apple-touch-startup-image"]')
      links.forEach((link) => link.remove())
    }
  }, [])

  return null
}
